insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Antiques','0.09','9999','UK');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Art','0.09','9999','UK');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Baby','0.09','9999','UK');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Books, Comics & Magazines','0.08','9999','UK');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Business, Office & Industrial','0.1','9999','UK');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Cameras & Photography>Camcorders','0.05','20','UK');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Cameras & Photography>Digital Cameras','0.05','20','UK');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Cameras & Photography> Film Photography','0.05','20','UK');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Cameras & Photography>Lenses & Filters ','0.05','20','UK');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Cameras & Photography','0.08','9999','UK');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Clothes, Shoes & Accessories','0.1','9999','UK');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Coins','0.09','9999','UK');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Collectables','0.09','9999','UK');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Computers/Tablets & Networking>Desktops & All-in-Ones','0.05','20','UK');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Computers/Tablets & Networking>Desktops & Drives, Storage & Blank Media','0.05','20','UK');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Computers/Tablets & Networking>Desktops & Enterprise Networking, Servers','0.05','20','UK');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Computers/Tablets & Networking>Desktops & Home Networking  & Connectivity','0.05','20','UK');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Computers/Tablets & Networking>Desktops & Tablets & eBook Readers','0.05','20','UK');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Computers/Tablets & Networking>Desktops & Laptops & Netbooks','0.05','20','UK');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Computers/Tablets & Networking>Desktops & Printers, Scanners & Suppliers','0.05','20','UK');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Computers/Tablets & Networking>Desktops & Software ','0.05','20','UK');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Computers/Tablets & Networking','0.08','9999','UK');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Crafts','0.11','9999','UK');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Dolls & Bears','0.09','9999','UK');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('DVDs, Films & TV','0.08','9999','UK');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Event Tickets','0.11','9999','UK');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Garden & Patio','0.09','9999','UK');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Health & Beauty','0.09','9999','UK');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Holidays & Travel','0.06','40','UK');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Home, Furniture & DIY>Appliances','0.05','20','UK');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Home, Furniture & DIY>DIY Tools','0.05','20','UK');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Home, Furniture & DIY>Furniture','0.09','40','UK');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Home, Furniture & DIY>Bath ','0.09','40','UK');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Home, Furniture & DIY','0.1','9999','UK');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Jewellery & Watches>Watches','0.1','50','UK');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Jewellery & Watches','0.11','9999','UK');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Mobile Phones & Communication>Home Phones & Accessories','0.05','20','UK');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Mobile Phones & Communication>Mobile & Smart Phones ','0.05','20','UK');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Mobile Phones & Communication>PDAs  ','0.05','20','UK');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Mobile Phones & Communication','0.08','9999','UK');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Music','0.08','9999','UK');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Musical Instruments','0.09','9999','UK');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Pet Supplies','0.11','9999','UK');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Pottery, Porcelain & Glass','0.09','9999','UK');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Sound & Vision>DVD, Blu-ray & Home Cinema','0.05','20','UK');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Sound & Vision>Headphones','0.05','20','UK');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Sound & Vision>Home Audio & HiFi Separates','0.05','20','UK');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Sound & Vision> iPods & MP3 Players','0.05','20','UK');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Sound & Vision>Televisions','0.05','20','UK');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Sound & Vision>TV Reception & Set-Top Boxes','0.05','20','UK');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Sound & Vision','0.08','9999','UK');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Sporting Goods','0.09','9999','UK');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Sports Memorabilia','0.09','9999','UK');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Stamps','0.09','9999','UK');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Toys & Games','0.09','9999','UK');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Vehicle Parts & Accessories>Tyres','0.06','15','UK');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Vehicle Parts & Accessories> Tyres & Tubes ','0.06','15','UK');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Vehicle Parts & Accessories> GPS & Sat Nav','0.05','20','UK');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Vehicle Parts & Accessories> Power Tools & Equipment ','0.05','20','UK');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Vehicle Parts & Accessories','0.07','9999','UK');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Video Games & Consoles>Consoles ','0.05','20','UK');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Video Games & Consoles','0.08','9999','UK');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Wholesale & Job Lots','0.11','9999','UK');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Everything Else','0.11','9999','UK');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Health & Beauty>Hair Extensions & Wigs','0.1','9999','UK');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Antiquitäten & Kunst','0.09','9999','DE');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Auto & Motorrad: Fahrzeuge','0.09','9999','DE');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Auto & Motorrad: Fahrzeuge>Automobile','0.085','9999','DE');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Auto & Motorrad: Fahrzeuge>Motorräder','0.085','9999','DE');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Auto & Motorrad: Fahrzeuge>Nutzfahrzeuge','0.085','9999','DE');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Auto & Motorrad: Fahrzeuge>Pkw-Anhänger','0.085','9999','DE');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Auto & Motorrad: Fahrzeuge>Wohnwagen & Wohnmobile','0.085','9999','DE');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Auto & Motorrad: Fahrzeuge>Fahrzeuge mit Leasingvertrag','0.085','9999','DE');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Auto & Motorrad: Fahrzeuge>Golfwagen','0.085','9999','DE');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Auto & Motorrad: Teile','0.09','9999','DE');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Baby','0.095','9999','DE');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Beauty & Gesundheit','0.09','9999','DE');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Briefmarken','0.09','9999','DE');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Business & Industrie','0.085','9999','DE');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Bücher','0.095','9999','DE');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Bücher>Bücherzubehör>Exlibris','0.09','9999','DE');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Büro & Schreibwaren','0.085','9999','DE');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Computer, Tablets & Netzwerk','0.085','9999','DE');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Computer, Tablets & Netzwerk>Tablet & eBook Zubehör','0.08','12','DE');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Computer, Tablets & Netzwerk>Notebook- & Desktop-Zubehör','0.08','12','DE');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Computer, Tablets & Netzwerk>Drucker, Scanner & Zubehör','0.08','9999','DE');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Computer, Tablets & Netzwerk>Drucker, Scanner & Zubehör>Drucker','0.05','9999','DE');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Computer, Tablets & Netzwerk>Drucker, Scanner & Zubehör>Scanner','0.05','10','DE');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Computer, Tablets & Netzwerk>Kabel & Steckverbinder','0.08','12','DE');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Computer, Tablets & Netzwerk>Tastaturen, Mäuse & Pointing','0.08','12','DE');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Feinschmecker','0.085','9999','DE');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Filme & DVDs','0.07','9999','DE');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Foto & Camcorder','0.05','10','DE');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Foto & Camcorder>Kamera- & Fotozubehör','0.08','12','DE');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Foto & Camcorder>Objektive & Filter','0.08','12','DE');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Foto & Camcorder>Stative & Zubehör','0.08','12','DE');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Garten & Terrasse','0.095','19','DE');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Handys & Kommunikation','0.05','10','DE');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Handys & Kommunikation>Handy- & PDA-Zubehör','0.08','12','DE');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Handys & Kommunikation>Handy- & PDA-Zubehör>Speicherkarten','0.05','10','DE');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Haushaltsgeräte','0.05','10','DE');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Haustierbedarf','0.085','9999','DE');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Heimwerker','0.095','19','DE');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Immobilien','0.085','9999','DE');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Kleidung & Accessoires','0.1','9999','DE');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Modellbau','0.085','9999','DE');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Musik','0.085','9999','DE');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Musikinstrumente','0.08','24','DE');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Möbel & Wohnen','0.09','9999','DE');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Münzen','0.09','9999','DE');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('PC- & Videospiele>PC- & Videospiele','0.07','9999','DE');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('PC- & Videospiele>Konsolen','0.05','10','DE');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('PC- & Videospiele>Zubehör','0.08','12','DE');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('PC- & Videospiele>Zubehör>Speicherkarten','0.05','10','DE');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('PC- & Videospiele>Ersatzteile & Werkzeuge','0.085','9999','DE');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('PC- & Videospiele>Game Cards','0.07','9999','DE');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('PC- & Videospiele>Lösungsbücher & Ratgeber','0.07','9999','DE');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('PC- & Videospiele>Merchandising>','0.07','9999','DE');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('PC- & Videospiele>Originalverpackungen & -hüllen','0.085','9999','DE');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('PC- & Videospiele>Spielanleitungen & Inserts','0.085','9999','DE');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('PC- & Videospiele>Sonstige','0.085','9999','DE');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Reisen','0.08','9999','DE');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Sammeln & Seltenes','0.09','9999','DE');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Spielzeug','0.095','9999','DE');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Sport','0.08','9999','DE');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Tickets','0.085','9999','DE');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('TV, Video & Audio','0.085','9999','DE');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('TV, Video & Audio>iPod- & MP3-Player-Zubehör','0.08','12','DE');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('TV, Video & Audio>TV- & Heim-Audio-Zubehör','0.08','12','DE');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('TV, Video & Audio>Haushaltsbatterien & Strom','0.08','12','DE');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Uhren & Schmuck','0.085','9999','DE');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Uhren & Schmuck>Armband- & Taschenuhren','0.095','47','DE');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Uhren & Schmuck>Weitere Uhren','0.095','47','DE');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Uhren & Schmuck>Sammleruhren','0.095','47','DE');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Uhren & Schmuck>Zubehör','0.08','12','DE');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Verschiedenes','0.085','9999','DE');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Antiques','0.09','250','US');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Art','0.09','250','US');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Baby','0.09','250','US');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Books','0.09','250','US');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Business & Industrial','0.09','250','US');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Business & Industrial>Healthcare, Lab & Life Science>Imaging & Aesthetics Equipment','0.04','250','US');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Business & Industrial>Heavy Equipment','0.04','250','US');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Business & Industrial>Printing & Graphic Arts>Commercial Printing Presses','0.04','250','US');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Business & Industrial>Restaurant & Catering>Concession Trailers & Carts','0.04','250','US');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Cameras & Photo','0.06','250','US');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Cameras & Photo>Camera & Photo Accessories','0.09','250','US');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Cameras & Photo>Camera & Photo Accessories>Memory Cards','0.06','250','US');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Cameras & Photo>Replacement Parts & Tools','0.09','250','US');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Cameras & Photo>Tripods & Supports','0.09','250','US');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Cameras & Photo>Other Cameras & Photo','0.09','250','US');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Cell Phones & Accessories','0.06','250','US');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Cell Phones & Accessories>Cell Phone Accessories','0.09','250','US');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Cell Phones & Accessories>Cell Phone Accessories>Memory Cards','0.06','250','US');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Cell Phones & Accessories>Other Cell Phones & Accs','0.09','250','US');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Clothing, Shoes & Accessories','0.09','250','US');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Coins & Paper Money','0.06','250','US');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Collectibles','0.09','250','US');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Computers/Tablets & Networking','0.06','250','US');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Computers/Tablets & Networking>Tablets & eBook Readers','0.04','250','US');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Computers/Tablets & Networking>Tablet & eBook Reader Accs','0.09','250','US');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Computers/Tablets & Networking>Tablet & eBook Reader Accs>Memory Card & USB Adapters','0.06','250','US');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Computers/Tablets & Networking>Laptops & Netbooks','0.04','250','US');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Computers/Tablets & Networking>Desktops & All-In-Ones','0.04','250','US');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Computers/Tablets & Networking>Laptop & Desktop Accessories','0.09','250','US');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Computers/Tablets & Networking>Computer Cables & Connectors','0.09','250','US');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Computers/Tablets & Networking>Computer Components & Parts>Motherboards','0.04','250','US');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Computers/Tablets & Networking>Computer Components & Parts>Motherboards & CPU Combos','0.04','250','US');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Computers/Tablets & Networking>Computer Components & Parts>CPUs/ Processors','0.04','250','US');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Computers/Tablets & Networking>Computer Components & Parts>Memory (RAM)','0.04','250','US');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Computers/Tablets & Networking>Drives, Storage & Blank Media>Hard Drives (HDD, SDD & NAS)','0.04','250','US');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Computers/Tablets & Networking>Keyboards, Mice & Pointers','0.09','250','US');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Computers/Tablets & Networking>Monitors, Projectors & Accs>Monitors','0.04','250','US');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Computers/Tablets & Networking>Power Protection, Distribution','0.09','250','US');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Computers/Tablets & Networking>Printers, Scanners & Supplies>Printers','0.04','250','US');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Computers/Tablets & Networking>Other Computers & Networking','0.09','250','US');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Consumer Electronics','0.09','250','US');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Crafts','0.09','250','US');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Dolls & Bears','0.09','250','US');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('DVDs & Movies','0.09','250','US');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('eBay Motors','0.09','250','US');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('eBay Motors>Parts & Accessories','0.08','250','US');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('eBay Motors>Parts & Accessories>Car Electronics','0.06','250','US');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('eBay Motors>Automotive Tools & Supplies','0.08','250','US');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Entertainment Memorabilia','0.09','250','US');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Gift Cards & Coupons','0.09','250','US');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Health & Beauty','0.09','250','US');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Home & Garden','0.09','250','US');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Jewelry & Watches','0.09','250','US');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Music','0.09','250','US');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Musical Instruments & Gear','0.07','250','US');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Musical Instruments & Gear>DJ Equipment','0.06','250','US');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Musical Instruments & Gear>Pro Audio Equipment','0.06','250','US');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Pet Supplies','0.09','250','US');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Pottery & Glass','0.09','250','US');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Real Estate','0.09','250','US');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Specialty Services','0.09','250','US');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Sporting Goods','0.09','250','US');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Sports Mem, Cards & Fan Shop','0.09','250','US');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Stamps','0.06','250','US');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Tickets & Experiences','0.09','250','US');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Toys & Hobbies','0.09','250','US');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Travel','0.09','250','US');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Video Games & Consoles','0.06','250','US');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Video Games & Consoles>Video Games','0.09','250','US');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Video Games & Consoles>Video Game Consoles','0.04','250','US');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Video Games & Consoles>Video Game Accessories','0.09','250','US');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Video Games & Consoles>Replacement Parts & Tools','0.09','250','US');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Video Games & Consoles>Other Video Games & Consoles','0.09','250','US');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Everything Else','0.09','250','US');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Bastel- & Künstlerbedarf','0.085','9999','DE');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Alcohol & Food','0.08','400','AU');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Antiques','0.08','400','AU');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Art','0.08','400','AU');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Baby','0.08','400','AU');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Books, Magazines','0.08','400','AU');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Business','0.08','400','AU');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Cameras','0.095','400','AU');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Clothing, Shoes, Accessories','0.095','400','AU');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Coins','0.08','400','AU');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Collectables','0.095','400','AU');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Computers/Tablets & Networking','0.095','400','AU');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Crafts','0.08','400','AU');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Dolls, Bears','0.08','400','AU');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Electronics','0.095','400','AU');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Gift Cards','0.08','400','AU');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Health & Beauty','0.095','400','AU');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Home & Garden','0.08','400','AU');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Home Appliances','0.08','400','AU');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Home Entertainment','0.095','400','AU');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Industrial','0.08','400','AU');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Jewellery & Watches','0.095','400','AU');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Movies','0.08','400','AU');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Music','0.08','400','AU');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Musical Instruments','0.08','400','AU');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Pet Supplies','0.08','400','AU');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Phones & Accessories','0.095','400','AU');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Pottery, Glass','0.08','400','AU');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Services','0.08','400','AU');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Sporting Goods','0.08','400','AU');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Stamps','0.08','400','AU');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Tickets, Travel','0.08','400','AU');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Toys, Hobbies','0.08','400','AU');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Vehicle Parts & Accessories','0.08','400','AU');
insert into t_ebay_fee (category_name,fee_rate,max_value,site_shortName) values ('Video Games & Consoles','0.095','400','AU');
